[WIP] Standardize and add SSL settings
logstash-plugins/logstash-input-beats pull request #470
Opened 2023-03-28 08:40 UTC by edmocosta

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

2023-03-30 14:44 UTC, edmocosta commented on lib/logstash/inputs/beats.rb
> +    @ssl_enabled && @ssl_peer_metadata && ssl_configured? && client_authentication_enabled?
I have added the `@ssl_enabled` here to fix an existing issue. When `ssl => false`, ` ssl_peer_metadata => true`, and `ssl_certificate_authorities` is configured, it tries to [extract the metadata ](https://github.com/logstash-plugins/logstash-input-beats/blob/main/lib/logstash/inputs/beats/message_listener.rb#L135) from the netty context and crashes as SSL is actually disabled.

2023-03-31 10:16 UTC, andsel requested changes
Overall seems good, but left some comments for improvement.

2023-03-31 10:16 UTC, andsel commented on src/main/java/org/logstash/netty/SslContextBuilder.java
> +        }
Maybe we could have a more explicit mapping without using the switch with:
```java
  NONE(ClientAuth.NONE),
  OPTIONAL(ClientAuth.OPTIONAL),
  REQUIRED(ClientAuth.REQUIRE);
  
  private final ClientAuth clientAuth;

  private SslClientVerifyMode(ClientAuth clientAuth) {
      this.clientAuth = clientAuth;
  }
   
  public ClientAuth toClientAuth() {
      return clientAuth;
  }
```

2023-03-31 10:16 UTC, andsel commented on src/main/java/org/logstash/netty/SslContextBuilder.java
> +            logger.debug(String.format("Ciphers: %s", Arrays.toString(ciphers)));
We can leverage the log4j templating and avoid the move to String format


```suggestion
            logger.debug("Available ciphers: {}", SUPPORTED_CIPHERS);
            logger.debug("Ciphers: {}", Arrays.toString(ciphers));
```

2023-03-31 10:16 UTC, andsel commented on src/main/java/org/logstash/netty/SslContextBuilder.java
> +                logger.debug(String.format("Certificate Authorities: %s", Arrays.toString(certificateAuthorities)));
```suggestion
                logger.debug("Certificate Authorities: {}", Arrays.toString(certificateAuthorities));
```

2023-03-31 10:16 UTC, andsel commented on src/test/java/org/logstash/netty/SslContextBuilderTest.java
> +import static org.hamcrest.Matchers.*;
Avoid `*` import switch to explicit list

2023-03-31 10:16 UTC, andsel commented on src/test/java/org/logstash/netty/SslContextBuilderTest.java
> +import static org.hamcrest.Matchers.*;
same for the following import of such kind

2023-03-31 10:16 UTC, andsel commented on src/test/java/org/logstash/netty/SslContextBuilderTest.java
> +            Assert.fail("No exception was thrown");
All the other `Assert` methods are statically imported, so maybe we could use the same pattern and move to `fail()`

2023-03-31 12:04 UTC, edmocosta commented on lib/logstash/inputs/beats.rb
> +    @ssl_client_authentication && @ssl_client_authentication.downcase == "required"
Hi @andsel, thanks for reviewing! I don't see much gain as well so I will keep it as it's.

2023-04-04 12:51 UTC, andsel approved these changes
LGTM

2023-04-05 12:43 UTC, merged